### ISSUE TITLE
D2 Fest Campus 문의사항용 이슈

### ISSUE THREAD

**Issue by OsoriAndOmori** [Web-Engine/pubg-minimap-replay#1]
안녕하세요. 네이버 스포츠에서 일하고 있는 김기훈 입니다 ^^;
제가 생각한 말도 안되는 어플리케이션 구현해주시느라 매우 고생많으셨습니다 ㅎㅎ 
게임을 좋아하시는 분들이라면 그나마 즐겁게 작업하지 않으셨을까 생각해봅니다. 
저도 고민하는 내내 즐거웠습니다.

행사 주최측에서 받은 가이드론 8월 14일까지 평가 제출 하라고 합니다. 
그래서 다음주 평일중으로 면밀하게 살펴볼 예정인데요.
고치고 싶은 부분이 있다면 중간중간 커밋 정도는 하셔도 될 것 같습니다. 
(이전 히스토리 바꾸는 force push 는 지양)

자주 들어올테니 저에게 궁금하신건 여기 이슈에 적어주셔도되고, 제 메일로 문의주셔도됩니다. 
메일을 잘보는 편이 아니라 사내, 개인메일을 동시에 보내주시면 인지를 좀 금방해서 보다 빨리 답변드릴수있습니다.
`skywhite15@korea.ac.kr` `skywhite15.kkh@navercorp.com` 

저 역시 테스트 도중에  문의사항 생기는 것은 요 이슈에 질문 하도록 하겠습니다.

끝으로 어떠한 결과가 나오더라도, 개발적인 이야기나 네이버 실제 서비스, 현업이야기 등등 
궁금한건 편하게 나눌 수 있는 좋은 관계가 되었으면 좋겠습니다~ 
감사합니다.

**Comment by Web-Engine** [comment]
안녕하세요! 이번 프로젝트 팀장을 맡은 조태상입니다.

말씀해주신 것처럼 팀원들과 개발하면서 하나씩 하나씩 완성되어 가는걸 보고 재미있게 프로젝트 진행했습니다.

처음에 프로젝트 주제를 잘못 이해하고 개발을 하다가 제출 3일 전쯤 제출 준비를 하다가 주제를 제대로 이해했습니다.

그래서 급하게 고치느라 원래 목표로 했던 완성도를 달성하지 못한 것 같아 조금 아쉬웠습니다.

따로 더 수정하고 싶은 부분은 브랜치를 나누어 개발 한 뒤에 완성 될 때마다 master에 병합하도록 하겠습니다.

궁금하신 점은 언제든지 깃허브 이슈나 메일(gsts007@gmail.com) 통해서 알려주시면 최대한 빨리 답 해드리도록 하겠습니다.

감사합니다.

**Comment by OsoriAndOmori** [comment]
말씀해주신 내용은 프로젝트 제출시 보내신 텍스트로 파악했습니다.

흔히 말하는 개발'스펙' 체크하는게 쉬운일은 아니죠 ^^; 
언어 영역 출제자의 의도를 파악한다거나... 그런거라, 
면밀하게 안보면 이상한 방향으로 개발하기 일쑤인것 같습니다. (저도 자주하는 ㅋㅋ)
제가 좀 더 명확하게 문제에 써놨으면 좋았을 것 같은데, 죄송하네요 고생하셨습니다 ㅎㅎ

추가적으로 필요한 부분있으면 연락드리겠습니다.

**Comment by OsoriAndOmori** [comment]
@Web-Engine 

### 요청사항 
안녕하세요 확인중에 있는데요. 

#### 1. 각 프로젝트 설명하는 README.md 도 좀 채워주시는게 좋을 것 같습니다. 
* pdf 내용을 좀 정리하면 될 것 같습니다.

#### 2. 제가 지금 혼동되는 부분이 있어서 전체적인 구조를 그림으로 설명을 해주시면 좋을 것 같습니다 ㅎ 아래가 맞을까요?
* pubg-replay - backend : 배그 Api 호출 하는 컴포넌트, 
Replay 도 하는것 같음.(이게 front에 있는게 맞을거 같긴한데), 
pubg-minimap-replay  빌드 결과물을 public/js/replay.js 경로로 두고 실행

* pubg-replay - frontend : 배그 Api 호출 받아서 기본 UI 화면 그리는 녀석, 그냥 화면만 보여주는 껍데기

#### 3. 기능적으로는 front 에서 제 id 넣고 search 해보면, 아무런 동작을 안하는데요.
* 관련해서 제가 테스트를 잘못한건지 확인한번 부탁드립니다~
* url 파라미터로 `아이디` `steam` 주고 들어가도 그러네요

![Aug-07-2019 13-40-48](https://user-images.githubusercontent.com/22016317/62595368-0d4d4700-b919-11e9-9e7a-973564a88968.gif)

#### 4. 그리고 편하게 테스트 위해서 데이터 컨버팅된 샘플데이터가 있으면 좋겠습니다.

**Comment by Web-Engine** [comment]
답변이 늦어져서 죄송합니다.

1. 네! pdf 문서도 markdown으로 작성한거라 조만간 README.md에 올리려고 했습니다. ㅎㅎ
곧 수정해서 커밋 하도록 하겠습니다.

2.
- pubg-replay - backend:
  - **GET /pubg/matches/:platform/:match_id**
    PUBG에서 제공하는 API를 통해 PUBG 리플레이 데이터를 받아와 저희가 정학 데이터 포맷으로 변경하는 기능이 들어있습니다.
    platform은 steam, kakao 등이 있고, match_id는 pubg.sh을 통해서 확인하시는게 편리하실 것 같습니다.

    pubg.sh 예시 주소: https://pubg.sh/PiedBouche/steam/ce0ff515-590e-46bf-8ae4-891196876ea1 에서 마지막 ce0ff515-590e-46bf-8ae4-891196876ea1가 match_id입니다.

  - **POST /check**
    사용자가 데이터를 제출하면 해당 데이터가 저희가 정한 포맷대로 구성되어 있는지 확인하는 기능이 들어 있습니다.
  - **GET /**
    pubg-minimap-replay에 있던 test 파일을 기반으로 replay를 볼 수 있는 웹 페이지를 보여줍니다.
 
- pubg-replay - frontend:
  - 배틀그라운드 게임에 맞춰 개발하다 보니, 맨 처음에는 pubg.sh와 유사한 사이트를 만드려고 계획했습니다. 그래서 제작한 Frontend는 Vue로 제작하였습니다.
  - 프로젝트 주제를 제대로 이해하고 나서 (모든 게임을 리플레이 할 수 있는 미니맵) 배틀그라운드에 맞춰 개발하지 않기 때문에 Frontend 부분은 개발을 중단하였습니다.
  - 결과적으로 지금은 사용되지 않습니다.

- pubg-minimap-replay: 
  - PIXI.js를 기반으로 포맷된 데이터를 넣으면 화면에 미니맵을 그려주는 라이브러리 입니다.

3.
위에서 말씀드렸다 싶이 pubg-replay - frontend는 현재 사용되지 않습니다.

4.
컨버팅 된 데이터는 곧 올려드리도록 하겠습니다.

**Comment by Web-Engine** [comment]
[test.zip](https://github.com/Web-Engine/pubg-minimap-replay/files/3476833/test.zip)

테스트 데이터입니다. test-1.json, test-2.json 두개의 파일을 압축하였습니다.
예시 사이트로 보내드린 http://13.125.196.60/ 에 접속하셔서 파일 선택하시면 리플레이를 보실 수 있습니다.

**Comment by OsoriAndOmori** [comment]
감사합니다. 이해했습니다.
더욱 프로젝트 정리와 사용법이 필요해보입니다. 
어찌되었건 평가는 제가 해서 디테일한 내용이나 개발은 모두 파악 했지만, 
결과물 자체는 다른 팀원들도 보고 같이 의견을 주고 받고 있어서요 ㅎㅎ

- pubg-replay - frontend 를 깔끔하게 지우기
- README.md 쓰기 (구조 설명 - 그림이 좋습니다, 명확한 리플레이 방법에 대한 기술)
가령 backend - install, start, Api key 발급, api요청, 받은 결과물 파일 선택창에서 로드, 플레이버튼 등등

**Comment by Web-Engine** [comment]
프로젝트 README 부분 다시 작성해서 올렸습니다.
아직 부족한 부분이 많아서 차차 수정하도록 하겠습니다.

말씀하셨던 pubg-replay의 frontend 부분은 branch를 나누어서 vue로 다시 제작 중입니다.
![image](https://user-images.githubusercontent.com/3965510/62758956-d9aa2280-baba-11e9-870d-5165471f1811.png)
다 완성되면 master branch에 병합하도록 하겠습니다.

README에 사진은 frontend 부분 완성 후에 함께 올리도록 하겠습니다!

+) 추가로 배틀그라운드 작업했던 부분도 조금 아쉬워서 다시 살려서 backend, frontend에 추가하려고 합니다.

**Comment by OsoriAndOmori** [comment]
축하드립니돠~~^^
이슈는 닫을게요

**Comment by Web-Engine** [comment]
감사합니다.
평가하시느라 수고하셨습니다.
